spring:
  application:
    name: week7
  cache:
    type: simple

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pracdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: hshs0415

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  header: Authorization
  prefix: "Bearer "
  secret: "a2FrYW90ZWNoYm9vdGNhbXBmdWxsc3RhY2sza2FrYW90ZWNoYm9vdGNhbXBmdWxsc3RhY2sz"
  token-expiration-time: 18000
  refresh-expiration-time: 604800

logging:
  level:
    org.springframework.cache: TRACE